[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/prenota"
  to = "/prenota.html"
  status = 200

[[redirects]]
  from = "/prenota/*"
  to = "/prenota.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
