-- Aggiunge accesso anon in lettura a tutte le chiavi impostazioni usate dal portale prenotazioni online
CREATE POLICY "anon_read_portale_prenotazioni" ON impostazioni
  FOR SELECT TO anon
  USING (chiave IN (
    'prenotazioni_online_attive',
    'portale_nascosto',
    'hair_quiz_attivo',
    'fasce_orarie_online_json',
    'annuncio_attivo',
    'annuncio_sfondo',
    'annuncio_testo',
    'annuncio_id',
    'annuncio_compleanno_testo',
    'azienda_telefono',
    'azienda_email',
    'azienda_pec',
    'azienda_indirizzo',
    'azienda_google_maps',
    'azienda_sito_prenotazioni',
    'azienda_note',
    'orari_salone_json',
    'orari_salone_nota',
    'ferie_inizio',
    'ferie_fine',
    'benvenuto_attivo',
    'benvenuto_config_json',
    'icona_pwa_url',
    'mostra_carta_premium_sbiadita',
    'social_instagram',
    'social_facebook',
    'social_tiktok',
    'social_youtube',
    'social_whatsapp',
    'social_x',
    'social_threads',
    'social_google_business',
    'social_tripadvisor',
    'social_altro'
  ));
